trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0

  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Use Node 20.x"

  # Usamos npm install para que NO requiera package-lock.json
  - script: npm install --no-audit --no-fund
    displayName: "Install deps"

  - script: npm test
    displayName: "Run tests"

  - script: npm run build
    displayName: "Build (optional)"
