trigger:
  branches: { include: [ main ] }
pr:
  branches: { include: [ main ] }

pool: { vmImage: ubuntu-latest }

steps:
  - checkout: self
    fetchDepth: 0

  - task: NodeTool@0
    inputs: { versionSpec: '20.x' }
    displayName: 'Use Node 20.x'

  - script: npm ci --no-audit --no-fund
    displayName: 'Install deps'

  - script: npm test --if-present
    displayName: 'Run tests'

  - script: npm run build --if-present
    displayName: 'Build (optional)'
